name: Primeiro Workflow Com Input
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
      inputs:
        Primeiro-Input: 
          description: Chave do Laboratorio
          required: true
  
jobs:
  PrimeiroJob:
    runs-on: ubuntu-latest
    steps:
      - name: Testando Input
        run: |
          echo Roando pela ${{ github.run_number }} vez!
          echo CONTEUDO DO INPUT: ${{ github.event.inputs.Primeiro-Input }}
