name: Primeiro Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  PrimeiroJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rodando Cript de Uma Linha
        run: echo Meu Primeiro Workflw

      - name: Rodando Script de Varias Linhas
        run: |
          echo Da pra fazer em mais de uma linha ! :D
          echo Olha sรณ que doideira !
          echo roando pela ${{ github.run_id }} vez!
